# Docker Compose configuration for the database in my local environment
# Author: Andrew Jarombek
# Date: 5/20/2020

version: '3.7'
services:
  apollo-client-server-prototype-db:
    domainname: apollo-client-server-prototype-db
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    environment:
      # Password is assigned to the default 'postgres' user.
      POSTGRES_PASSWORD: apollolocal
    ports:
      - 5432:5432
    networks:
      - local-apollo-client-server-net

networks:
  local-apollo-client-server-net:
    driver: bridge
